name: Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install C++ toolchain
        uses: numworks/setup-arm-toolchain@latest
      - name: Run make (3D Points])
        run: cd src/points && make
      - name: Run make (Not Calculation)
        run: cd src/not_calc && make
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nwa-files
          path: src/**/*.nwa